stop_instance:
vast_api_key: "fyll inn"

dataset: "navjordj/SNL_summarization"
model_name: "navjordj/t5-base-snl"
n_samples:
eval_batch_size: 16
fp16: False

base_config:
- max_length: 150
- num_beams: 1
- num_beam_groups: 1
- do_sample: False
- no_repeat_ngram_size: 0 
- encoder_no_repeat_ngram_size: 0
- temperature: 1
- top_k: 50
- top_p: 1.0
- repetition_penalty: 1.0
- eta_cutoff: 0.0 # https://arxiv.org/pdf/2210.15191.pdf

configs:

  # beam searches
  beam:
  - num_beams: 5

  beam_no_repeat_ngram_size_3:
  - no_repeat_ngram_size: 3
  - num_beams: 5

  beam_no_repeat_ngram_size_5:
  - no_repeat_ngram_size: 5
  - num_beams: 5


  beam_encoder_no_repeat_ngram_size_5:
  - encoder_no_repeat_ngram_size: 5
  - num_beams: 5


  beam_repetition_12:
  - repetition_penalty: 1.2
  - num_beams: 5

  # greedy  

  greedy:



  # sampling configs
  sample_top_k_50:
  - do_sample: True
  - top_k: 50

  sample_temperature_12_top_k_50:
  - temperature: 0.7
  - do_sample: True
  - top_k: 50

  sample_temperature_12_top_k_50:
  - temperature: 1.2
  - do_sample: True
  - top_k: 50

  sample_top_p_07:
  - top_p: 0.7
  - do_sample: True

  sample_top_p_095:
  - top_p: 0.95
  - do_sample: True

  sample_eta_00006:
  - do_sample: True
  - eta_cutoff: 0.0006

  sample_eta_00003:
  - do_sample: True
  - eta_cutoff: 0.0003





  


